# SET FACT
# - alpine_release
# - alpine_version
# - alpine_arch
# - linux_kernel_flavor

- block:
  - stat:
      path: /etc/alpine-release.apk-new
    register: result
  - name: alpine | use alpine-release.apk-new
    shell: mv /etc/alpine-release.apk-new /etc/alpine-release
    become: true
    when: result.stat.exists
  - name: alpine | release
    slurp:
      src: "/etc/alpine-release"
    register: result
  - set_fact:
      alpine_release: "{{ result.content | b64decode | trim }}"
  when: alpine_release is not defined

- name: alpine | version
  set_fact:
    alpine_version: "{{ alpine_release | regex_search('^[0-9]+[.][0-9]+') }}"

- block:
  - name: alpine | kernel flavor
    shell: uname -r | grep -E -o '\w+$' | tr -d '\n'
    register: result
    changed_when: false
  - set_fact:
      linux_kernel_flavor: "{{ result.stdout }}"
  when: linux_kernel_flavor is not defined

- block:
  - name: alpine | apk arch
    shell: apk --print-arch
    register: result
    changed_when: false
  - set_fact:
      alpine_arch: "{{ result.stdout | trim }}"
  when: alpine_arch is not defined

- name: alpine | preset
  debug:
    msg:
      - "Alpine Release: {{ alpine_release }}"
      - "Alpine Version: {{ alpine_version }}"
      - "APK Arch: {{ alpine_arch }}"
      - "Kernel Flavor: {{ linux_kernel_flavor }}"
  tags:
    - debug
