- name: apk repo | remove repo
  become: true
  lineinfile:
    path: /etc/apk/repositories
    regex: "^[^#]*?{{ alpine_mirror }}/v{{ alpine_version }}/{{ item }}"
    state: absent
  loop:
    - main
    - community
  when: apk_repo is not defined

- name: apk repo | remove apk_repo
  become: true
  lineinfile:
    path: /etc/apk/repositories
    regex: "^[^#]*?{{ apk_repo }}"
    state: absent
  when: apk_repo is defined
