- name: apk repo | add mirror
  become: true
  lineinfile:
    path: /etc/apk/repositories
    line: "{{ alpine_mirror }}/v{{ alpine_version }}/{{ item }}"
    regex: "^[^#]*?{{ alpine_mirror }}/v{{ alpine_version }}/{{ item }}"
    state: present
  loop:
    - main
    - community
  when: apk_repo is not defined

- name: apk repo | add  apk_repo
  become: true
  lineinfile:
    path: /etc/apk/repositories
    line: "{{ apk_repo }}"
    regex: "^[^#]*?{{ apk_repo }}"
    state: present
  when: apk_repo is defined
