# - name: apk | check version
#   assert:
#     that:
#     - alpine_version is defined
#     - alpine_mirror is defined

- name: apk | repositories {{alpine_version}}
  become: true
  copy:
    dest: /etc/apk/repositories
    content: |
      {{ alpine_mirror }}/v{{ alpine_version }}/main
      {{ alpine_mirror }}/v{{ alpine_version }}/community
      {{ apk_repositories_extra | default('') }}
