- name: dnsmasq | install
  become: true
  apk:
    name: dnsmasq
  when: dnsmasq_dnssec is undefined

# dnsmasq with dnssec support - conflict with dnsmasq
- name: dnsmasq | install dnsmasq-dnssec (optional)
  become: true
  apk:
    name: dnsmasq-dnssec
  when: dnsmasq_dnssec is defined

- name: dnsmasq | conf
  include_tasks: dnsmasq-conf.yaml

- name: dnsmasq | start service
  become: true
  service:
    name: dnsmasq
    state: started
    enabled: true
