# include /etc/dnsmasq.d
- name: dnsmasq conf | include dnsmasq.d
  become: true
  lineinfile:
    path: /etc/dnsmasq.conf
    line: conf-dir=/etc/dnsmasq.d
    create: true
    regex: '^\s*conf-dir='
    mode: 0644
  when: dnsmasq_include_dir is undefined or dnsmasq_include_dir
  notify: dnsmasq-reload

- name: dnsmasq conf | write inline resolv.dnsmasq.conf
  become: true
  copy:
    dest: /etc/resolv.dnsmasq.conf
    mode: 0644
    content: |
      {{ dnsmasq_resolv_conf }}
  when: dnsmasq_resolv_conf is defined
  notify: dnsmasq-reload

- name: dnsmasq conf | conf-dir resolv.dnsmasq.conf
  become: true
  lineinfile:
    path: /etc/dnsmasq.d/resolv.conf
    line: resolv-file=/etc/resolv.dnsmasq.conf
    create: true
    regex: '^\s*resolv-file='
    mode: 0644
  when: dnsmasq_include_dir is undefined or dnsmasq_include_dir
  notify: dnsmasq-reload

- name: dnsmasq conf | sync dnsmasq.conf
  include_role:
    name: alpine
    tasks_from: service-conf-sync
  vars:
    service_name: dnsmasq
    service_conf_dest_path: /etc/dnsmasq.conf
    service_conf_file: dnsmasq.conf
    service_notify_type: restart

- name: dnsmasq conf | sync resolv.conf
  include_role:
    name: alpine
    tasks_from: service-conf-sync
  vars:
    service_name: dnsmasq
    service_conf_dest_path: /etc/resolv.dnsmasq.conf
    service_conf_file: resolv.conf
    service_notify_type: restart

- name: dnsmasq conf | sync dnsmasq.d
  include_role:
    name: alpine
    tasks_from: service-conf-sync
  vars:
    service_name: dnsmasq
    service_conf_dest_path: /etc/dnsmasq.d
    service_conf_file: dnsmasq.d
    service_conf_delete: true
    service_notify_type: restart

- name: dnsmasq conf | stat /etc/resolv.dnsmasq.conf
  stat:
    path: /etc/resolv.dnsmasq.conf
  register: stat
- name: dnsmasq conf | fallback to /etc/resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.dnsmasq.conf
    remote_src: true
  when: not stat.stat.exists
  become: true
