- import_tasks: docker-install.yaml

- import_tasks: docker-daemon-conf.yaml

- name: cgroups | enable
  become: true
  service:
    name: cgroups
    enabled: true
    state: started

- name: docker | start on bootstrap
  become: true
  service:
    name: docker
    state: started
    enabled: true
