- name: haproxy | install
  become: true
  apk:
    name: "{{ item }}"
  loop:
    - haproxy

- import_tasks: haproxy-conf.yaml

- name: haproxy | start
  become: true
  service:
    name: haproxy
    state: started
    enabled: true
