# - name: debug hostname
#   ansible.builtin.debug:
#     msg:
#     - "{{hostname|default('n/a')}}"
#     - "{{inventory_hostname}}"

- name: set hostname to "{{ hostname|default(inventory_hostname) }}"
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname|default(inventory_hostname) }}"
    use: alpine

- name: set /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: '{{ item }} {{ hostname|default(inventory_hostname) }}'
    state: present
  loop:
    - "127.0.0.1"
    - "::1"
