- name: k3s | machine-id | enable
  become: true
  service:
    name: machine-id
    enabled: true
    state: started
    runlevel: default
- name: k3s | cgroups | enable
  become: true
  service:
    name: cgroups
    enabled: true
    state: started
- name: k3s | install deps
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
  - coreutils
  - findutils
  - iptables
  - musl
  - iproute2
  - nfs-utils
  - rsync

- include_tasks: k3s-fetch.yaml
