- name: k3s | fetch /etc/rancher/k3s/k3s.yaml
  become: true
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ inv_name | default('.') }}/files/kubeconfig-{{ inventory_hostname }}.yaml"
    flat: true
