# stop
- name: k3s | stop
  become: true
  service:
    name: k3s
    state: stopped
    runlevel: default

# fetch
- include_tasks: k3s-fetch.yaml

# upgrade
- name: k3s | backup last
  copy:
    src: /usr/local/bin/k3s
    dest: /data/opt/k3s/k3s.last
    mode: 0755
    remote_src: true

- name: k3s | install
  become: true
  copy:
    src: /data/opt/k3s/k3s
    dest: /usr/local/bin/k3s
    mode: 0755
    remote_src: true

# start
- name: k3s | start
  become: true
  service:
    name: k3s
    state: started
    runlevel: default
