- name: longhorn | install deps
  become: true
  apk:
    name: "{{item}}"
  loop:
  - open-iscsi
  - curl
  - findmnt
  - grep
  - gawk
  - blkid
  - lsblk
  - util-linux
  - nfs-utils

- name: longhorn | start iscsi
  become: true
  service:
    name: iscsid
    state: started
    enabled: true
