- name: root passwd | from Values
  set_fact:
    root_password_plain: "{{ Values.root_password_plain }}"
  when:
    - root_password_plain is undefined
    - Values is defined
    - Values.root_password_plain is defined
- name: update root password
  become: true
  user:
    name: root
    password: "{{ root_password_plain | password_hash('sha512', root_password_salt | default(999999999|random)) }}"
