- name: install packages for ops
  become: true
  apk:
    name: "{{ item }}"
  loop:
    - bash
    - bash-completion
    - tmux
    - mosh
    - file
    - tree
    - rsync
    - htop
    # fancy monitor
    - btop
    # procps for < 3.17
    - procps-ng
    - lsof
    # 网络
    - iftop
    - tcpdump
    # for dig
    - bind-tools
    # info
    #- neofetch
    - fastfetch
    - util-linux
    - util-linux-bash-completion
    # sshrc needs
    - xxd
    - tar
    - coreutils
    - openssl

# common op service
# crond local
