# will not keep tzdata pkg after copy and link
- name: setup timezone
  become: true
  command: setup-timezone -z Asia/Shanghai
  # TODO
  changed_when: false

# /etc/keymap - will not keep keymap pkg
# rc-update add loadkmap boot
- name: setup keymap
  become: true
  command: setup-keymap us us
  # TODO
  changed_when: false

- import_tasks: ntp-service.yaml
- import_tasks: machine-id.yaml

# poweroff or reset works
- name: enable acpid
  become: true
  service:
    name: acpid
    enabled: true
    state: started
    runlevel: default

# device hotplug
# - name: enable mdev when no udev
#   service:
#       name: mdev
#       enabled: true
#       state: started
#       runlevel: sysinit
