- name: sockd | install
  become: true
  apk:
    name: "{{ item }}"
  loop:
  - dante-server

- name: sockd | inline sockd.conf
  become: true
  copy:
    dest: /etc/sockd.conf
    content: "{{ sockd_conf }}"
    mode: 0644
  when: sockd_conf is defined
  notify: sockd-reload

- name: sockd | start
  become: true
  service:
    name: sockd
    state: started
    enabled: true
