- name: tinc | start tinc.{{ tinc_netname }} service
  become: true
  service:
    name: tinc.{{ tinc_netname }}
    state: started
    enabled: true
  when: tinc_netname is defined

- name: tinc | start tinc.{{ tinc_netnames }} service
  become: true
  service:
    name: tinc.{{ item }}
    state: started
    enabled: true
  when: tinc_netnames is defined
  loop: "{{ tinc_netnames }}"
