- name: zfs | ensure udev
  include_tasks: ensure-service.yaml
  vars:
    - service_name: udev

- setup:
  when: ansible_kernel is undefined
  name: zfs | gather

- name: zfs | install zfs with kernal {{ ansible_kernel }}
  become: true
  apk:
    name: "{{ item }}"
  loop:
    - zfs
    - zfs-udev
    - "zfs-{{ ansible_kernel | regex_search('-([a-z]*?)$','\\1') | first | default('lts') }}"

- name: zfs | load zfs module
  become: true
  modprobe:
    name: zfs
    state: present

- name: zfs | persist zfs mpdule
  become: true
  lineinfile:
    path: /etc/modules-load.d/zfs.conf
    line: zfs
    create: true
    mode: 0644

- name: zfs | start zfs
  become: true
  service:
    name: "{{ item }}"
    state: started
  loop:
    - zfs-import
    - zfs-mount
  tags:
    - service-start

- name: zfs | enable zfs on boot
  become: true
  service:
    name: "{{ item }}"
    enabled: true
    runlevel: sysinit
  loop:
    - zfs-import
    - zfs-mount
  tags:
    - service-enable
