- name: run adhoc tasks
  hosts: all
  gather_facts: false
  roles:
    - alpine
  collections:
    - wenerme.alpine
  tasks:
    - add_host:
        name: "{{ host | default('alpine_host') }}"
        ansible_ssh_host: "{{ host | default('127.0.0.1') }}"
        ansible_ssh_port: "{{ port | default('22') }}"
      when: port is defined or host is defined
      name: adhoc | add default host

    - setup:
      when: facts | default(false)
      name: adhoc | setup
    - include_role:
        name: "{{ role | default('alpine') }}"
        tasks_from: "{{ task }}"
      name: adhoc | run role task
