- name: Upgrade and Reboot
  hosts: all
  vars_prompt:
    - name: do_reboot
      prompt: "Do you need to reboot (if openssh is upgraded preffer reboot)?"
      private: false
      default: false
  roles:
    - alpine
  collections:
    - wenerme.alpine
  tasks:
    - import_role:
        name: alpine
        tasks_from: apk-repo
      vars:
        alpine_version: "3.15"
      name: apk-repo
    - import_role:
        name: alpine
        tasks_from: apk-version
      name: apk-version

    - name: nothing to upgrade
      meta: end_play
      when: (apk_upgradable_count|int) == 0

    - pause:
        seconds: 10
        prompt: will upgrade now...
      name: wait

    - import_role:
        name: alpine
        tasks_from: apk-upgrade
      vars:
        apk_upgrade_all: true
      name: run task role

    - name: reboot
      become: true
      raw: reboot
      when: do_reboot|bool
